### ISSUE TITLE
usage example

### ISSUE THREAD

**Issue by aep** [LoupVaillant/Monokex#4]
i'm a little confused how to use it, since it doesnt follow the noise api

from the generated code (unfortunately i dont know ocaml at all), it looks like crypto_kex_read MUSt be followed by crypto_kex_write 

```C
  213     // Next time, we'll send
--214     ctx->flags |= SHOULD_SEND;

```

so this is for query response type of protocols only?

or is the intend that you extract the final cypher somehow after completing the handshake?

**Comment by LoupVaillant** [comment]
> it looks like crypto_kex_read MUSt be followed by crypto_kex_write

Don't read too much into the internal flags. Which action should be performed next depends on several flags. The comment is not entirely accurate, though, maybe I should change it. The header file is full of comments, they are supposed to be enough (even though they almost certainly not).

*Someone* has to be the last to send, so the other one will actually finish by a read. And then call the `final()` function so it gets the session keys.

> so this is for query response type of protocols only?

Not it works for the one way patterns too.

> or is the intend that you extract the final cypher somehow after completing the handshake?

Yep, that's right: the `final()` function is used for that: once the handshake is complete, you call that function and get your session keys.

---

More generally, the exact order of the actions you must perform depends on the pattern. You can hard code that order, or you can use `crypto_kex_next_action()` to query what should be done next. The possible actions are as follow:

- __Init:__ The first action.
- __Prelude:__ Optional, just after initialisation. Used to add a prelude to the transcript, just like Noise.
- __Read: __ Receive a message. Typically follows (and is followed by) a write, but not always. Pay special attention to message sizes.
- __Write:__ Send a message. Typically follows (and is followed by) a read, but not always. Pay special attention to message sizes.
- __Remote:__ Get the remote key that was just sent. Must be called after a read that contains the remote public key. (The XK1 pattern for instance requires the server to get the remote key right after the last read.)
- __Final:__ The last action. Gets the session keys and wipes the context.

Each action has its dedicated function. Reads and writes have *two* dedicated functions each: a basic one, that just deal with a handshake message, and a more advanced one that also handles payloads. I personally don't encourage early payloads, but sometimes we do need them.
